"""Compute the backup options and generate the backup scripts.

The options are read from, in increasing order of importance:

- the ``[tool.collective-backup]`` table in ``pyproject.toml``,
- a ``.env`` file,
- environment variables.

Option ``keep`` is read from ``COLLECTIVE_BACKUP_KEEP``, ``blob_storage`` from
``COLLECTIVE_BACKUP_BLOB_STORAGE``, etcetera.  Relative paths are relative to
``base_dir``, by default the directory with the ``pyproject.toml``, or else
the current directory.
"""

from collective.backup import main
from collective.backup import utils
from collective.backup.utils import construct_path
from collective.backup.utils import to_bool

import argparse
import logging
import os
import pprint
import re
import shutil
import sys

try:
    import tomllib
except ImportError:  # Python 3.10
    import tomli as tomllib

logger = logging.getLogger("backup")

# Standard storage key for Data.fs.
STORAGE_KEY = "1"
ENV_PREFIX = "COLLECTIVE_BACKUP_"
ENV_FILE = ".env"
PYPROJECT = "pyproject.toml"
PYPROJECT_TABLE = "collective-backup"
# Options that we only use for the crontab.
CRON_OPTIONS = ("cron", "snapshot_cron")
# First line after the shebang of each generated script.  We use it to
# recognize scripts that we may remove when they are no longer generated.
MARKER = "# Generated by collective.backup"

BOOLEAN_OPTIONS = (
    "archive_blob",
    "backup_blobs",
    "blob_timestamps",
    "compress_blob",
    "debug",
    "enable_snapshotrestore",
    "enable_zipbackup",
    "full",
    "incremental_blobs",
    "only_blobs",
    "rsync_hard_links_on_first_copy",
    "use_rsync",
)
LOCATION_OPTIONS = (
    "location",
    "snapshotlocation",
    "blobbackuplocation",
    "blobsnapshotlocation",
    "ziplocation",
    "blobziplocation",
)
KNOWN_OPTIONS = set(BOOLEAN_OPTIONS + LOCATION_OPTIONS) | {
    "alternative_restore_source",
    "bin_dir",
    "blob_storage",
    "datafs",
    "keep",
    "keep_blob_days",
    "locationprefix",
    "post_command",
    "pre_command",
    "repozo",
    "rsync_options",
    "var_dir",
}

# Command name (script name when the name is 'backup') and the function
# in collective.backup.main that it calls.
COMMANDS = {
    "backup": "backup_main",
    "zipbackup": "zipbackup_main",
    "snapshotbackup": "snapshot_main",
    "restore": "restore_main",
    "ziprestore": "zip_restore_main",
    "snapshotrestore": "snapshot_restore_main",
    "altrestore": "alt_restore_main",
}
DESCRIPTIONS = {
    "backup": "Make a backup of the filestorage and blobstorage.",
    "zipbackup": "Make a zipped backup of the filestorage and blobstorage.",
    "snapshotbackup": "Make a full snapshot backup.",
    "restore": "Restore the latest backup, or the one at the given date.",
    "ziprestore": "Restore the zipped backup.",
    "snapshotrestore": "Restore the latest snapshot backup.",
    "altrestore": "Restore from the alternative restore source.",
}


class ConfigError(Exception):
    """Error in the configuration."""


def script_names(name):
    """Return the script names for a part with this name.

    The name 'backup' gets the standard names.  Other names are used
    as prefix.

    >>> script_names('backup')['snapshotbackup']
    'snapshotbackup'
    >>> script_names('plonebackup')['snapshotbackup']
    'plonebackup-snapshot'
    >>> script_names('plonebackup')['backup']
    'plonebackup'
    """
    if name == "backup":
        return {
            "backup": "backup",
            "zipbackup": "zipbackup",
            "snapshotbackup": "snapshotbackup",
            "restore": "restore",
            "snapshotrestore": "snapshotrestore",
            "altrestore": "altrestore",
            "ziprestore": "ziprestore",
            "blobstoragebackup": "blobstoragebackup",
            "blobstoragesnapshot": "blobstoragesnapshot",
            "blobstoragezip": "blobstoragezip",
        }
    return {
        "backup": name,
        "zipbackup": name + "-zip",
        "snapshotbackup": name + "-snapshot",
        "restore": name + "-restore",
        "snapshotrestore": name + "-snapshotrestore",
        "altrestore": name + "-altrestore",
        "ziprestore": name + "-ziprestore",
        "blobstoragebackup": name + "-blobstorage",
        "blobstoragesnapshot": name + "-blobstoragesnapshot",
        "blobstoragezip": name + "-blobstoragezip",
    }


def read_env_file(path):
    """Read variables from a .env file.

    Lines have the form ``NAME=value``, optionally prefixed with ``export``.
    Values may be quoted.  Like in docker compose, double quoted values
    may contain escapes like ``\\n``.  Empty lines and comments are ignored.
    """
    result = {}
    with open(path, encoding="utf-8") as myfile:
        for number, line in enumerate(myfile, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[len("export ") :].lstrip()
            name, sep, value = line.partition("=")
            if not sep:
                raise ConfigError(f"{path}, line {number}: expected NAME=value.")
            value = value.strip()
            if len(value) >= 2 and value[0] == value[-1] == "'":
                value = value[1:-1]
            elif len(value) >= 2 and value[0] == value[-1] == '"':
                # Like docker compose, we support escapes in double quotes.
                value = re.sub(
                    r"\\(.)",
                    lambda match: {"n": "\n", "t": "\t"}.get(
                        match.group(1), match.group(1)
                    ),
                    value[1:-1],
                )
            result[name.strip()] = value
    return result


def options_from_env(environ):
    """Get the options from the COLLECTIVE_BACKUP_* variables.

    >>> options_from_env({'COLLECTIVE_BACKUP_KEEP': '3', 'HOME': '/root'})
    {'keep': '3'}
    """
    return {
        name[len(ENV_PREFIX) :].lower(): value
        for name, value in environ.items()
        if name.startswith(ENV_PREFIX)
    }


def read_pyproject(path):
    """Read the [tool.collective-backup] table from a pyproject.toml file.

    Return the options as strings, like the environment variables.
    """
    try:
        with open(path, "rb") as myfile:
            data = tomllib.load(myfile)
    except tomllib.TOMLDecodeError as exc:
        raise ConfigError(f"Cannot parse {path}: {exc}")
    table = data.get("tool", {}).get(PYPROJECT_TABLE, {})
    if not isinstance(table, dict):
        raise ConfigError(f"[tool.{PYPROJECT_TABLE}] in {path} must be a table.")
    options = {}
    for key, value in table.items():
        key = key.lower().replace("-", "_")
        if isinstance(value, bool):
            value = "true" if value else "false"
        elif isinstance(value, int):
            value = str(value)
        elif not isinstance(value, str):
            raise ConfigError(
                f"Option {key} in [tool.{PYPROJECT_TABLE}] of {path} "
                f"must be a string, boolean or integer, not {value!r}."
            )
        options[key] = value
    return options


def has_table(path):
    """Does this pyproject.toml file have a [tool.collective-backup] table?"""
    try:
        with open(path, "rb") as myfile:
            data = tomllib.load(myfile)
    except (OSError, tomllib.TOMLDecodeError):
        return False
    return PYPROJECT_TABLE in data.get("tool", {})


class Config:
    """The combined options from pyproject.toml, .env and the environment."""

    def __init__(self, config=None, env_file=None, environ=None):
        if environ is None:
            environ = os.environ
        self.config_path = None
        if config:
            if not os.path.isfile(config):
                raise ConfigError(f"Configuration file {config} not found.")
            self.config_path = os.path.abspath(config)
        elif has_table(PYPROJECT):
            self.config_path = os.path.abspath(PYPROJECT)
        # The directory where we look for .env, and relative paths start.
        if self.config_path:
            self.directory = os.path.dirname(self.config_path)
        else:
            self.directory = os.path.abspath(os.curdir)

        options = {}
        if self.config_path:
            options.update(read_pyproject(self.config_path))
        self.env_file = None
        if env_file:
            if not os.path.isfile(env_file):
                raise ConfigError(f"Environment file {env_file} not found.")
            self.env_file = os.path.abspath(env_file)
        elif os.path.isfile(os.path.join(self.directory, ENV_FILE)):
            self.env_file = os.path.join(self.directory, ENV_FILE)
        if self.env_file:
            options.update(options_from_env(read_env_file(self.env_file)))
        options.update(options_from_env(environ))
        self.options = options

    def part(self):
        """Return a Part with these options."""
        options = dict(self.options)
        for key in CRON_OPTIONS:
            options.pop(key, None)
        name = options.pop("name", "") or "backup"
        base_dir = construct_path(self.directory, options.pop("base_dir", "") or ".")
        return Part(name, options, base_dir)


def load_part(env_file=None, environ=None, config=None):
    """Load the options and return a Part."""
    return Config(config=config, env_file=env_file, environ=environ).part()


def find_repozo(base_dir, value, bin_dir):
    """Find the repozo script.

    With an explicit value, we use that.  Otherwise we look in the bin
    directory of the scripts, then next to the current Python, and then on
    the PATH.
    """
    if value:
        if os.sep in value:
            return construct_path(base_dir, value)
        return shutil.which(value) or value
    next_to_python = os.path.join(os.path.dirname(sys.executable), "repozo")
    for candidate in (os.path.join(bin_dir, "repozo"), next_to_python):
        if os.path.exists(candidate):
            return candidate
    return shutil.which("repozo") or next_to_python


class Part:
    """One set of backup scripts with its options."""

    def __init__(self, name, options, base_dir):
        self.name = name
        self.base_dir = base_dir
        self.options = options = dict(options)
        unknown = sorted(set(options) - KNOWN_OPTIONS)
        if unknown:
            logger.warning(
                "Ignoring unknown option(s): %s",
                ", ".join(f"{key} ({ENV_PREFIX}{key.upper()})" for key in unknown),
            )
            for key in unknown:
                del options[key]
        options.setdefault("blob_storage", "")

        options.setdefault("backup_blobs", "True")

        # Validate options, checking for example that the locations are unique.
        self.validate()
        self.compute()

    def compute(self):
        """Compute all options, the storage, and the script arguments."""
        options = self.options
        base_dir = self.base_dir
        self.names = names = script_names(self.name)
        self.bin_dir = construct_path(base_dir, options.setdefault("bin_dir", "bin"))
        var_dir = construct_path(base_dir, options.setdefault("var_dir", "var"))

        prefix = options.get("locationprefix")
        if prefix is not None:
            prefix = construct_path(base_dir, prefix)
        else:
            prefix = var_dir

        def default_location(key):
            return os.path.abspath(os.path.join(prefix, names[key] + "s"))

        # locations, alphabetical
        options.setdefault("blobbackuplocation", default_location("blobstoragebackup"))
        options.setdefault(
            "blobsnapshotlocation", default_location("blobstoragesnapshot")
        )
        options.setdefault("blobziplocation", default_location("blobstoragezip"))
        options.setdefault("location", default_location("backup"))
        options.setdefault("snapshotlocation", default_location("snapshotbackup"))
        options.setdefault("ziplocation", default_location("zipbackup"))

        # Validate options, checking that the locations are unique
        self.validate()

        # more options, alphabetical
        options.setdefault("alternative_restore_source", "")

        options.setdefault("archive_blob", "false")
        options.setdefault("blob_timestamps", "true")
        options.setdefault("compress_blob", "false")
        options.setdefault("datafs", os.path.join(var_dir, "filestorage", "Data.fs"))
        options.setdefault("debug", "false")
        options.setdefault("enable_snapshotrestore", "true")
        options.setdefault("enable_zipbackup", "false")
        options.setdefault("full", "false")
        options.setdefault("incremental_blobs", "false")
        options.setdefault("keep", "2")
        options.setdefault("keep_blob_days", "14")  # two weeks
        options.setdefault("only_blobs", "false")
        options.setdefault("post_command", "")
        options.setdefault("pre_command", "")
        options.setdefault("rsync_options", "")
        options.setdefault("use_rsync", "true")
        options.setdefault("rsync_hard_links_on_first_copy", "false")

        # Get the blob storage.  We only default to var/blobstorage when we
        # backup blobs: an explicit blob_storage is used for altrestore too.
        blob_storage = options["blob_storage"]
        if blob_storage:
            blob_storage = construct_path(base_dir, blob_storage)
        elif to_bool(options["backup_blobs"]):
            blob_storage = os.path.join(var_dir, "blobstorage")
        options["blob_storage"] = blob_storage

        if to_bool(options["incremental_blobs"]):
            # Incremental blobs only work with timestamped file names.
            options["blob_timestamps"] = "true"

        # Validate again, which also sets the truth values correctly.
        self.validate()

        if not to_bool(options["blob_timestamps"]):
            # blob_timestamps was explicitly set to false
            logger.warning(
                "You have disabled blob_timestamps. "
                "Support for this may be dropped in a future version, "
                "making it impossible to restore backups without timestamps."
            )

        # More locations.
        backup_location = construct_path(prefix, options["location"])
        snapshot_location = construct_path(prefix, options["snapshotlocation"])
        zip_location = construct_path(prefix, options["ziplocation"])

        # Blob backup.
        if to_bool(options["backup_blobs"]):
            blob_backup_location = construct_path(prefix, options["blobbackuplocation"])
            blob_snapshot_location = construct_path(
                prefix, options["blobsnapshotlocation"]
            )
            blob_zip_location = construct_path(prefix, options["blobziplocation"])
        else:
            blob_backup_location = ""
            blob_snapshot_location = ""
            blob_zip_location = ""

        self.storage = self.compute_storage(
            backup_location=backup_location,
            snapshot_location=snapshot_location,
            zip_location=zip_location,
            blob_backup_location=blob_backup_location,
            blob_snapshot_location=blob_snapshot_location,
            blob_zip_location=blob_zip_location,
        )
        self.arguments = self.compute_arguments()

    def compute_storage(
        self,
        backup_location,
        snapshot_location,
        zip_location,
        blob_backup_location,
        blob_snapshot_location,
        blob_zip_location,
    ):
        # We support one filestorage: the standard Data.fs.
        datafs = construct_path(self.base_dir, self.options["datafs"])

        # '1' is the default root storagename for Zope.
        storage = dict(
            storage=STORAGE_KEY,
            datafs=datafs,
            blobdir=self.options["blob_storage"].rstrip(os.sep),
            backup_location=backup_location,
            snapshot_location=snapshot_location,
            zip_location=zip_location,
        )

        if storage["blobdir"]:
            storage["blob_backup_location"] = blob_backup_location
            storage["blob_snapshot_location"] = blob_snapshot_location
            storage["blob_zip_location"] = blob_zip_location

        # Handle alternative restore sources.
        return self.compute_alternative_restore_source(storage)

    def compute_alternative_restore_source(self, storage):
        """Compute alternative restore source.

        Return them in the storage.
        Only one source is supported: for the standard Data.fs.
        """
        alt_sources = self.options["alternative_restore_source"]
        if not alt_sources:
            return storage
        found = False
        alt_regex = (
            r"^\s*(?P<storage>[^\s]+)"
            r"\s+(?P<datafs>[^\s]+)"
            r"\s*(?P<blobdir>[^\s]*)\s*$"
        )
        for a in alt_sources.split("\n"):
            a = a.strip()
            if not a:
                continue
            if a.startswith("#"):
                continue
            if found:
                raise ConfigError(
                    "Only one alternative_restore_source line is supported."
                )
            found = True
            match = re.match(alt_regex, a)
            if match is None:
                raise ConfigError(
                    "alternative_restore_source line {!r} has a wrong "
                    "format. Should be: 'storage-name "
                    "filestorage-backup-path', optionally followed by "
                    "a blobstorage-backup-path.".format(a)
                )
            source = match.groupdict()
            key = orig_key = source["storage"]
            if key == "Data":
                key = STORAGE_KEY  # Data.fs is called storage '1'.
            if key != STORAGE_KEY:
                raise ConfigError(
                    "alternative_restore_source key {!r} unknown. "
                    "Expected 1 or Data.".format(orig_key)
                )
            storage["alt_location"] = construct_path(self.base_dir, source["datafs"])
            blobdir = source["blobdir"]
            if storage["blobdir"]:
                if not blobdir:
                    raise ConfigError(
                        "alternative_restore_source key {!r} is "
                        "missing a blobdir.".format(orig_key)
                    )
                storage["blob_alt_location"] = construct_path(self.base_dir, blobdir)
            elif blobdir:
                raise ConfigError(
                    "alternative_restore_source key {!r} specifies "
                    "blobdir {!r} but the original storage has no "
                    "blobstorage.".format(orig_key, blobdir)
                )
            else:
                storage["blob_alt_location"] = ""

        return storage

    def compute_arguments(self):
        """Return the keyword arguments for the functions in main."""
        options = self.options

        def to_int(key):
            try:
                return int(options[key])
            except ValueError:
                raise ConfigError(
                    f"Option {key} ({ENV_PREFIX}{key.upper()}) must be a number."
                )

        return dict(
            repozo=find_repozo(self.base_dir, options.get("repozo"), self.bin_dir),
            storage=self.storage,
            keep=to_int("keep"),
            keep_blob_days=to_int("keep_blob_days"),
            full=to_bool(options["full"]),
            verbose=to_bool(options["debug"]),
            only_blobs=to_bool(options["only_blobs"]),
            backup_blobs=to_bool(options["backup_blobs"]),
            use_rsync=to_bool(options["use_rsync"]),
            rsync_options=options["rsync_options"],
            archive_blob=to_bool(options["archive_blob"]),
            compress_blob=to_bool(options["compress_blob"]),
            pre_command=options["pre_command"],
            post_command=options["post_command"],
            blob_timestamps=to_bool(options["blob_timestamps"]),
            incremental_blobs=to_bool(options["incremental_blobs"]),
            rsync_hard_links_on_first_copy=to_bool(
                options["rsync_hard_links_on_first_copy"]
            ),
        )

    def commands(self):
        """Return the enabled commands with their script names.

        This is a dict of command (like 'snapshotbackup') to script name
        (like 'snapshotbackup' or 'plonebackup-snapshot').
        """
        options = self.options
        enabled = ["backup"]
        if to_bool(options["enable_zipbackup"]):
            enabled.append("zipbackup")
        enabled.extend(["snapshotbackup", "restore"])
        if to_bool(options["enable_zipbackup"]):
            enabled.append("ziprestore")
        if to_bool(options["enable_snapshotrestore"]):
            enabled.append("snapshotrestore")
        if options["alternative_restore_source"]:
            enabled.append("altrestore")
        return {command: self.names[command] for command in enabled}

    def check_folders(self):
        """Check that we can create the backup folders.

        We try to create the folders, but remove them again.
        """
        storage = self.storage
        if not to_bool(self.options["only_blobs"]):
            utils.try_create_folder(storage["backup_location"])
            utils.try_create_folder(storage["snapshot_location"])
        if to_bool(self.options["backup_blobs"]):
            utils.try_create_folder(storage["blob_backup_location"])
            utils.try_create_folder(storage["blob_snapshot_location"])

    def validate(self):
        options = self.options
        check_for_true(options, BOOLEAN_OPTIONS)

        # These must be distinct locations.
        locations = {}
        for opt in LOCATION_OPTIONS:
            value = options.get(opt)
            if value:
                locations[opt] = value
        if len(locations.keys()) != len(set(locations.values())):
            raise ConfigError(
                "These must be distinct locations:\n"
                + "\n".join([f"{k} = {v}" for (k, v) in sorted(locations.items())])
            )

        if not to_bool(options.get("backup_blobs")):
            if to_bool(options.get("only_blobs")):
                raise ConfigError("Cannot have backup_blobs false and only_blobs true.")
            if to_bool(options.get("enable_zipbackup")):
                raise ConfigError(
                    "Cannot have backup_blobs false and enable_zipbackup "
                    "true. zipbackup is useless without blobs."
                )
        if not to_bool(options.get("blob_timestamps", True)):
            # blob_timestamps was explicitly set to false
            if to_bool(options.get("incremental_blobs")):
                raise ConfigError(
                    "Cannot have blob_timestamps false and incremental_blobs true."
                )


def check_for_true(options, keys):
    """Set the truth options right.

    Default value is False, set it to True only if we're passed the string
    'true' or 'True'. Unify on a capitalized True/False string.
    """
    for key in keys:
        if key not in options:
            continue
        if to_bool(options[key]):
            options[key] = "True"
        else:
            options[key] = "False"


SCRIPT_TEMPLATE = """#!{executable}
{marker}
# Configuration: {source}
# Do not edit: run 'collective-backup generate' to regenerate this script.
import sys

from collective.backup.scripts import run_script


ARGUMENTS = {arguments}

if __name__ == "__main__":
    sys.exit(run_script({command!r}, ARGUMENTS))
"""


def generated_by(path):
    """Return the configuration source of a script that we generated.

    Return None if the file was not generated by us.
    """
    try:
        with open(path, encoding="utf-8") as myfile:
            lines = [myfile.readline() for _ in range(3)]
    except (OSError, UnicodeDecodeError):
        return None
    if lines[1].rstrip("\n") != MARKER:
        return None
    prefix = "# Configuration: "
    if not lines[2].startswith(prefix):
        return None
    return lines[2][len(prefix) :].rstrip("\n")


def generate(part, bin_dir=None):
    """Generate the scripts for the part and return their paths.

    Scripts that we generated earlier for the same part,
    but that are no longer wanted, are removed.
    """
    part.check_folders()
    dest = bin_dir or part.bin_dir
    if not os.path.isdir(dest):
        os.makedirs(dest)
    source = f"{part.name} in {part.base_dir}"
    arguments = pprint.pformat(part.arguments)
    generated = []
    for command, script_name in part.commands().items():
        path = os.path.join(dest, script_name)
        with open(path, "w", encoding="utf-8") as myfile:
            myfile.write(
                SCRIPT_TEMPLATE.format(
                    executable=sys.executable,
                    marker=MARKER,
                    source=source,
                    arguments=arguments,
                    command=command,
                )
            )
        os.chmod(path, 0o755)
        print(f"Generated script '{path}'.")
        generated.append(path)

    # Remove scripts that are no longer wanted.
    for filename in sorted(os.listdir(dest)):
        path = os.path.join(dest, filename)
        if path in generated or not os.path.isfile(path):
            continue
        if generated_by(path) == source:
            os.remove(path)
            print(f"Removed script '{path}'.")
    return generated


def add_script_arguments(parser, command):
    """Add the command line arguments of the scripts to a parser."""
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_false",
        dest="verbose",
        default=True,
        help="do not print status messages to stdout",
    )
    parser.add_argument(
        "-n",
        "--no-prompt",
        action="store_true",
        dest="no_prompt",
        default=False,
        help="do not ask for any user confirmation",
    )
    if "restore" in command:
        parser.add_argument(
            "date",
            nargs="?",
            help="restore the state at this date, in UTC: yyyy-mm-dd[-hh[-mm[-ss]]]",
        )


def execute(command, arguments, args):
    """Execute a command with the parsed command line arguments."""
    loglevel = logging.DEBUG if arguments.get("verbose") else logging.INFO
    # Allow the user to make the script more quiet (say in a cronjob):
    if not args.verbose:
        loglevel = logging.WARN
    log_format = "%(levelname)s: %(message)s"
    if loglevel < logging.INFO:
        log_format = "%(asctime)s " + log_format
    logging.basicConfig(level=loglevel, format=log_format, force=True)
    kwargs = dict(arguments)
    kwargs["no_prompt"] = args.no_prompt
    if "restore" in command:
        kwargs["date"] = args.date
    func = getattr(main, COMMANDS[command])
    return func(**kwargs)


def run_script(command, arguments, argv=None):
    """Run a command.  This is called by the generated scripts."""
    parser = argparse.ArgumentParser(description=DESCRIPTIONS[command])
    add_script_arguments(parser, command)
    args = parser.parse_args(argv)
    return execute(command, arguments, args)
